# .github/steps/install_dependencies/action.yml
name: Install Dependencies
description: "Installs .NET SDK and OS-specific dependencies"

inputs:
  job-platform:
    description: 'The target platform (windows, macos, linux)'
    required: true
  dotnet-version:
    description: 'Installs and sets the .NET SDK Version'
    required: false
    default: '9.0.x' 
  windows-sdk-version:
    description: 'Windows SDK version (Windows only)'
    required: false
    default: '26100' 

runs:
  using: "composite"
  steps:
    # 1. Install .NET 9 SDK
    - name: Setup .NET ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: '${{ inputs.dotnet-version }}'

    # 2. Install Windows SDK (Windows Only)
    - name: Install Windows SDK ${{ inputs.windows-sdk-version }}
      shell: pwsh
      if: runner.os == 'Windows' && inputs.job-platform == 'windows'
      run: |
        Write-Host "Installing Windows SDK version: ${{ inputs.windows-sdk-version }}"
        $sdkIsoScript = Join-Path $env:GITHUB_WORKSPACE ".github\Install-WindowsSdkISO.ps1"
        if (Test-Path $sdkIsoScript) {
          & $sdkIsoScript ${{ inputs.windows-sdk-version }} 
        } else {
          Write-Warning "Script not found at $sdkIsoScript. Skipping."
        }

    # 3. Install GTK Dependencies (Linux Only - Required for Skia.Gtk)
    - name: Install GTK Dependencies
      shell: bash
      if: runner.os == 'Linux' && inputs.job-platform == 'linux'
      run: |
        echo "Installing GTK dependencies..."
        sudo apt-get update
        
    # Run Uno.Check
    - name: Install ${{ inputs.target-platform }} Workloads
      shell: pwsh
      run: |
        dotnet tool install -g uno.check
        ("${{ inputs.target-platform }} ".Split(' ') | ForEach-Object {
          $target = $_.Replace("_win", "").Replace("_macos", "")
          if (![string]::IsNullOrEmpty($target)) {
            echo "target: $target"
            uno-check -v --ci --non-interactive --fix --target $target --skip vswin --skip vsmac --skip xcode --skip vswinworkloads --skip androidemulator --skip dotnetnewunotemplates
            echo "uno-check finished for target: $target "
          }
        })
