# .github/steps/install_dependencies/action.yml
name: Install Dependencies
description: "Installs .NET SDK, OS-specific SDKs/dependencies, and Uno workloads"

inputs:
  job-platform:
    description: 'The target platform for the current job (windows, macos, linux)'
    required: true
  dotnet-version:
    description: 'Installs and sets the .NET SDK Version'
    required: false
    # UPDATED: Default to .NET 9.x based on project requirements
    default: '9.0.x' 
  windows-sdk-version:
    description: 'The version of the Windows SDK to install (Windows only)'
    required: false
    # UPDATED: Default to match the project's Windows target framework (26100)
    default: '26100' 

runs:
  using: "composite"
  steps:
    # Install .NET SDK
    - name: Setup .NET ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: '${{ inputs.dotnet-version }}'

    # Install Windows SDK (Windows Runner Only)
    - name: Install Windows SDK ${{ inputs.windows-sdk-version }}
      shell: pwsh
      if: runner.os == 'Windows' && inputs.job-platform == 'windows'
      run: |
        Write-Host "Attempting to install Windows SDK version: ${{ inputs.windows-sdk-version }}"
        $sdkIsoScript = Join-Path $env:GITHUB_WORKSPACE ".github\Install-WindowsSdkISO.ps1"
        if (Test-Path $sdkIsoScript) {
          # Ensure your script can handle the specified version
          & $sdkIsoScript ${{ inputs.windows-sdk-version }} 
        } else {
          Write-Warning "Windows SDK ISO installation script not found at $sdkIsoScript. Skipping SDK installation. Build might fail if required SDK components are missing."
        }

    # Install GTK Dependencies (Linux Runner Only - for Skia.Gtk/Desktop)
    - name: Install GTK Dependencies
      shell: bash
      if: runner.os == 'Linux' && inputs.job-platform == 'linux'
      run: |
        echo "Installing GTK dependencies for Skia.Gtk/Desktop..."
        sudo apt-get update
        sudo apt-get install -y snapd
        sudo snap install core24
        sudo snap install multipass
        sudo snap install lxd
        sudo snap install snapcraft --classic
        lxd init --minimal
        sudo usermod --append --groups lxd $USER # In order for the current user to use LXD


    # Install Uno Check Tool and Run Check for the target platform
     - name: Install Uno Platform Workloads via uno-check for ${{ inputs.job-platform }}
      shell: pwsh
      run: |
        Write-Host "Installing/Updating uno-check tool..."
        # Install or update uno-check (non-fatal)
        dotnet tool update -g uno.check 2>$null || dotnet tool install -g uno.check

        $unoTarget = "${{ inputs.job-platform }}"
        if ($unoTarget -eq 'linux') { $unoTarget = 'desktop' }

        Write-Host "Running uno-check for target: $unoTarget"

        # Save a log file for diagnostics
        $timeStamp = (Get-Date).ToString('yyyyMMdd-HHmmss')
        $logFile = Join-Path $env:RUNNER_TEMP "uno-check-$($unoTarget)-$timeStamp.log"

        # Run uno-check and capture stdout/stderr
        & uno-check --ci --non-interactive --fix --target $unoTarget --skip vswin --skip vsmac --skip xcode --skip vswinworkloads --skip androidemulator --skip dotnetnewunotemplates --skip mauiinstallationcheck 2>&1 | Tee-Object -FilePath $logFile
        $unoExit = $LASTEXITCODE

        if ($unoExit -ne 0) {
            Write-Warning "uno-check completed with errors (Exit Code: $unoExit) for target $unoTarget. Build might fail."
            Write-Host "uno-check log saved to: $logFile"

            # If the composite action input requests failing on uno-check, propagate the non-zero exit.
            if ('${{ inputs.fail-on-uno-check }}' -eq 'true') {
                Write-Error "Failing job because inputs.fail-on-uno-check == true and uno-check returned $unoExit."
                exit $unoExit
            } else {
                Write-Warning "Continuing the workflow despite uno-check failures (inputs.fail-on-uno-check != true)."
                # Explicitly return success from this step so the composite action doesn't fail here.
                exit 0
            }
        } else {
            Write-Host "uno-check finished successfully for target: $unoTarget"
        }

