name: ðŸ› Bug Report
description: Create a bug report to help improve Emerald
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: â±ï¸ Before you start...
      options:
        - label: Are you on the latest version of Emerald? You might be using an old version.
          required: true
        - label:  I have checked if a similar issue has not already been reported
          required: true
  - type: textarea
    attributes:
      label: ðŸªŸ What build of Windows is this issue present? (optional)
      description: Windows key + R > winver.exe
      placeholder: build 25174.1010
  - type: textarea
    attributes:
      label: ðŸ”¢ What version of Emerald are you on?
      description: Go to Emerald > Settings > About
    validations:
      required: true
  - type: textarea
    attributes:
      label: ðŸ“„ Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ðŸªœ Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: ðŸ¤” Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ðŸ“¸ Assets
      description: |
        A list of assets (errors, screenshots) relevant to the bug.
