using Emerald.Services;
using Microsoft.Extensions.Logging;

namespace Emerald.CoreX.Services;

public interface IMinecraftBaseSettingsService
{
    const string EmeraldDataFolderName = "EmeraldData";

    const string HeaderComment = "// Do not edit this file manually. Emerald manages this file and manual changes may be overwritten.";

    string? CurrentBasePath { get; }

    bool IsInitialized { get; }

    void UseBasePath(string basePath);

    T Get<T>(string key, T defaultVal);

    void Set<T>(string key, T value);

    bool Exists(string key);

    void Delete(string key);
}

public sealed class MinecraftBaseSettingsService : IMinecraftBaseSettingsService
{
    private readonly ILogger<BaseSettingsService> _baseSettingsLogger;
    private BaseSettingsService? _settingsService;

    public MinecraftBaseSettingsService(ILogger<BaseSettingsService> baseSettingsLogger)
    {
        _baseSettingsLogger = baseSettingsLogger;
    }

    public string? CurrentBasePath { get; private set; }

    public bool IsInitialized => _settingsService != null;

    public void UseBasePath(string basePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(basePath);

        if (string.Equals(CurrentBasePath, basePath, StringComparison.OrdinalIgnoreCase) && _settingsService != null)
        {
            return;
        }

        var dataPath = Path.Combine(basePath, IMinecraftBaseSettingsService.EmeraldDataFolderName);
        Directory.CreateDirectory(dataPath);

        CurrentBasePath = basePath;
        _settingsService = new BaseSettingsService(
            _baseSettingsLogger,
            dataPath,
            IMinecraftBaseSettingsService.HeaderComment);
    }

    public T Get<T>(string key, T defaultVal)
        => Current.Get(key, defaultVal);

    public void Set<T>(string key, T value)
        => Current.Set(key, value);

    public bool Exists(string key)
        => IsInitialized && Current.Exists(key);

    public void Delete(string key)
    {
        if (IsInitialized)
        {
            Current.Delete(key);
        }
    }

    private BaseSettingsService Current
        => _settingsService ?? throw new InvalidOperationException("Minecraft base settings have not been initialized.");
}
